### ISSUE TITLE
DW conditionally approved

### ISSUE THREAD

**Issue by jonalf** [mmiah00/finalproject#1]
The idea is approved, but I have questions about your design. If this is a networked game, then the use of shared memory/signals seems odd. Those are only good when programs are running on the same computer, not on multiple computers connected via a network. Please update your design and respond to this issue when you have done so.

**Comment by mmiah00** [comment]
Hi Mr DW, 
We have updated the Technical Design section of the proposal. We plan our game to use files and processes to keep track of what moves have been made and different states of each board.

**Comment by jonalf** [comment]
Approved.
Make it so.
